// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import type { PaymentSettings } from "../../src/lib/payments/domain";
const mocks = vi.hoisted(() => ({ save: vi.fn(), refresh: vi.fn(), success: vi.fn() }));
vi.mock("../../src/app/admin/payments/actions", () => ({ selectPaymentProviderAction: mocks.save }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh: mocks.refresh }) }));
vi.mock("sonner", () => ({ toast: { success: mocks.success } }));
import { PaymentProviderSettings } from "../../src/app/admin/payments/provider-settings";
const settings: PaymentSettings = { activeProvider: "stripe", providers: [{ id: "stripe", configured: true }, { id: "netopia", configured: true }] };
beforeEach(() => { vi.clearAllMocks(); mocks.save.mockResolvedValue({ ok: true, activeProvider: "netopia" }); });
afterEach(cleanup);
it("balances configuration and selection sections, initializes persisted selection, and saves explicitly", async () => {
  render(<PaymentProviderSettings settings={settings} />);
  const section = screen.getByRole("region", { name: "Payment providers" });
  expect(section.className).toContain("grid-cols-1");
  expect(section.className).toContain("lg:grid-cols-2");
  expect(screen.getByRole("table", { name: "Provider configuration" })).toBeTruthy();
  const select = screen.getByRole("combobox");
  expect(select).toHaveProperty("value", "stripe");
  const save = screen.getByRole("button", { name: "Save changes" });
  expect(save).toHaveProperty("disabled", true);
  fireEvent.submit(save.closest("form")!);
  expect(mocks.save).not.toHaveBeenCalled();
  fireEvent.change(select, { target: { value: "netopia" } });
  expect(save).toHaveProperty("disabled", false);
  expect(mocks.save).not.toHaveBeenCalled();
  expect(screen.getByText("Persisted active provider: Stripe")).toBeTruthy();
  fireEvent.change(select, { target: { value: "stripe" } });
  expect(save).toHaveProperty("disabled", true);
  fireEvent.change(select, { target: { value: "netopia" } });
  fireEvent.click(save);
  await waitFor(() => expect(screen.getByText("Persisted active provider: NETOPIA")).toBeTruthy());
  expect(mocks.save).toHaveBeenCalledExactlyOnceWith({ provider: "netopia" });
  expect(save).toHaveProperty("disabled", true);
  expect(screen.getByRole("status").textContent).toBe("Payment provider settings saved.");
  expect(mocks.refresh).toHaveBeenCalledOnce();
});
it("keeps unconfigured providers disabled and rejects invalid selections", () => {
  render(<PaymentProviderSettings settings={{ ...settings, providers: [{ id: "stripe", configured: true }, { id: "netopia", configured: false }] }} />);
  expect(screen.getByRole("option", { name: "NETOPIA — not configured" })).toHaveProperty("disabled", true);
  fireEvent.change(screen.getByRole("combobox"), { target: { value: "netopia" } });
  const save = screen.getByRole("button", { name: "Save changes" });
  expect(save).toHaveProperty("disabled", true);
  fireEvent.submit(save.closest("form")!);
  expect(mocks.save).not.toHaveBeenCalled();
});
it.each([false, true])("preserves failed selection for retry and blocks duplicate pending saves (throws=%s)", async (throws) => {
  let finish!: () => void;
  mocks.save.mockReturnValueOnce(new Promise((resolve, reject) => { finish = () => throws ? reject(new Error("network")) : resolve({ ok: false, message: "Unable to save." }); }));
  render(<PaymentProviderSettings settings={settings} />);
  const select = screen.getByRole("combobox");
  fireEvent.change(select, { target: { value: "netopia" } });
  const form = screen.getByRole("button", { name: "Save changes" }).closest("form")!;
  fireEvent.submit(form);
  expect(select).toHaveProperty("disabled", true);
  expect(screen.getByRole("button", { name: "Saving…" })).toHaveProperty("disabled", true);
  fireEvent.submit(form);
  expect(mocks.save).toHaveBeenCalledOnce();
  finish();
  await screen.findByRole("alert");
  expect(select).toHaveProperty("value", "netopia");
  expect(screen.getByText("Persisted active provider: Stripe")).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Save changes" }));
  await waitFor(() => expect(screen.getByText("Persisted active provider: NETOPIA")).toBeTruthy());
  expect(mocks.save).toHaveBeenCalledTimes(2);
});
it("allows explicitly disabling online payments", async () => {
  mocks.save.mockResolvedValue({ ok: true, activeProvider: null });
  render(<PaymentProviderSettings settings={settings} />);
  fireEvent.change(screen.getByRole("combobox"), { target: { value: "" } });
  fireEvent.click(screen.getByRole("button", { name: "Save changes" }));
  await waitFor(() => expect(mocks.save).toHaveBeenCalledExactlyOnceWith({ provider: null }));
  expect(screen.getByText("Persisted active provider: Not selected")).toBeTruthy();
});
